language: ruby
rvm:
  - 2.2
gemfile:
  - GemFile
install: 
  - gem install jekyll 
  - bundle install
  - gem install s3_website
script: bundle exec jekyll build
after_success: s3_website push --force
branches:
  only:
    - master