title: I'm in a Cloud!
description: >
  **I am Patrick**, I'm a guy who always manages to find himself neck deep in the Cloud, and someone who likes to break it. 
  I also tend to get drunk sometimes.
copyright: Patrick Hudson
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: 
facebook_username:
twitter_username: 
linkedin_username: "hudsonpatrick"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "patrick-hudson"
feed_icon: rss
email: "phudson2@gmail.com"
gems: 
  - jekyll-paginate
paginate_path: "/page/:num/"
paginate: 5
permalink: /:categories/:title/