title: Technical ramblings of a DevOps Engineer
description: >
  **I am Patrick**, DevOps Engineer and Whiskey Enthusiest
copyright: Patrick Hudson
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname:
facebook_username:
twitter_username: "iamcloudguy"
linkedin_username: "hudsonpatrick"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "patrick-hudson"
feed_icon: rss
email: "phudson2@gmail.com"
gems:
  - jekyll-paginate
paginate_path: "/page/:num/"
paginate: 5
permalink: /:categories/:title/
